language: csharp
solution: CognitiveSocialFrames/CognitiveSocialFrames.sln
install:
  - nuget restore CognitiveSocialFrames/CognitiveSocialFrames.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release CognitiveSocialFrames/CognitiveSocialFrames.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./CognitiveSocialFrames/tests/bin/Release/MyProject.Tests.dll