name: .NET Core

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      solution: ./CognitiveSocialFrames/CognitiveSocialFrames.sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore $solution
    - name: Build
      run: dotnet build $solution --configuration Release --no-restore
    - name: Test
      run: dotnet test $solution --no-restore --verbosity normal
