name: .NET Core

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build CognitiveSocialFrames/CognitiveSocialFrames.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test CognitiveSocialFrames/CognitiveSocialFrames.sln --no-restore --verbosity normal
