name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      solution: ./CognitiveSocialFrames/CognitiveSocialFrames.sln
      buildPath: ./CognitiveSocialFrames/source/bin/Release/netcoreapp3.1/CognitiveSocialFrames.dll
      projectPath: CognitiveSocialFrames/source/source.csproj
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore $solution
    - name: Build
      run: dotnet build $solution --configuration Release --no-restore
    - name: Test
      run: dotnet test $solution --no-restore --verbosity normal
    - name: Extract Version from .csproj
      run: echo ::set-env name=TAG::$(cat ${{env.projectPath}} | grep -o "<Version>(.*)</Version>")
    - name: Print Version 
      run: echo ${{env.TAG}}